# https://github.com/itzg/docker-minecraft-bedrock-server/blob/master/examples/docker-compose.yml
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-bedrock-server
    restart: always
    environment:
      # Enable SSH
      ENABLE_SSH: true
      # Server settings
      EULA: "TRUE"
      GAMEMODE: survival
      SERVER_NAME: Papai Maluco
      LEVEL_NAME: Luizalandia
      # LEVEL_SEED: -2746961253358476370
      DIFFICULTY: normal
      ALLOW_CHEATS: false
      ALLOW_LIST: false
      CLIENT_SIDE_CHUNK_GENERATION_ENABLED: false # Beware: enabling this may cause stuttering/freezing
      MAX_THREADS: 0 # Maximum threads
      VIEW_DISTANCE: 20
      OPS: 2533274916143691
    # Expose the mc-server-runner's SSH port to just the backup container
    expose:
      - 2222
    ports:
      - "19132:19132/udp"
    volumes:
      - ./bedrock_server:/data
    stdin_open: true
    tty: true

  backup:
    container_name: backup
    image: kaiede/minecraft-bedrock-backup
    restart: always
    depends_on:
      # Make sure the minecraft service starts before the backup
      minecraft:
        condition: service_healthy
    volumes:
      # Map your backups folder into /backups
      - ./backups:/backups
      # Map the data folders for the server
      - ./bedrock_server:/bedrock_server
      # (Optional) Map a configuration folder separately from the backups.
      - ./backups-config:/config

  websocket:
    container_name: websocket
    image: joanroig/admincraft-websocket:latest
    restart: always
    depends_on:
      # Make sure the minecraft service starts before the websockets service
      minecraft:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      #- /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket
      - //var/run/docker.sock:/var/run/docker.sock # Mount Docker socket Windows
      - ./certs:/usr/src/app/certs:ro
    environment:
      SECRET_KEY: 3dc3abf6a7ce3a3aa681a7873e33c9dc9f9d30159898cf623bff50d6814d8075
      USE_SSL: "false" # Change to "false" to disable SSL

  unmined-gui:
    container_name: unmined
    image: ich777/unmined:latest
    restart: always
    depends_on:
      # Make sure the minecraft service starts before the websockets service
      minecraft:
        condition: service_healthy
    environment:
      CUSTOM_RES_W: 1280
      CUSTOM_RES_H: 850
      UID: 99
      GID: 100
      UMASK: 000
      DATA_PERM: 770
    ports:
      - 8085:8080
    volumes:
      - ./unmined:/unmined
      - ./bedrock_server/worlds/Luizalandia:/unmined/worlds:ro